<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D068G7Q" failures="1" tests="7" name="com.kuda.testCases.CustomerAccountManagement" time="41.430" errors="0" timestamp="2022-03-13T22:09:54 WAT" skipped="0">
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="viewCASAccount" time="15.511"/>
  <system-out>
Login Test Completed Successfully  </system-out>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="searchByAccountName" time="0.003"/>
  <system-out/>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="searchByAccountNumber" time="0.002"/>
  <system-out/>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="searchByAccountEmail" time="0.001"/>
  <system-out/>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="viewAccountBalance" time="0.002"/>
  <system-out/>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="editCustomerAccount" time="0.004"/>
  <system-out/>
  <testcase classname="com.kuda.testCases.CustomerAccountManagement" name="createCustomerAccount" time="25.907">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.kuda.testCases.CustomerAccountManagement.createCustomerAccount(CustomerAccountManagement.java:249)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createCustomerAccount -->
  <system-out>
Create casa button is clicked  </system-out>
</testsuite> <!-- com.kuda.testCases.CustomerAccountManagement -->
